
server:
  port: 8081
spring:
  application:
    name: arms-user
  profiles:
    active: default
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ioe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: ABC7758521abc
    url: jdbc:mysql://localhost:3306/ioe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
dubbo:
  scan:
    base-packages: com.coco.naruto.arms.user.dubbo
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
